version: '3.1'

services:
  postgres-db:
    build: ./postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432

  virtual-machines-app:
    build: .
    depends_on:
      - postgres-db
    ports:
      - 8080:8080
      - 6006:6006

